---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-6.4

suites:
  - name: default
    run_list: [
      'recipe[apt]',
      'recipe[git]',
      'recipe[mysql::server]',
      'recipe[mysql::client]',
      'recipe[java]',
      'recipe[l1j]'
      ]
    attributes:
      java:
        jdk_version: 7
      mysql:
        server_debian_password: 'password'
        server_root_password: 'password'
        server_repl_password: 'password'
